version: 0.0
os: linux

files:
  - source: ./
    destination: /var/www/html

hooks:
  ApplicationStart:
    - location: /var/www/html/test/start.sh
      runas: root
      timeout: 300

  ApplicationStop:
    - location: /var/www/html/test/stop.sh
      runas: root
      timeout: 300
