# version: 0.0
# os: linux

# files:
#   - source: ./app
#     destination: /opt/apps

# hooks:
#   ApplicationStop:
#     - location: app/scripts/stop.sh
#       runas: root

#   ApplicationStart:
#     - location: app/scripts/start.sh
#       runas: root
version: 0.0
os: linux
files:
  - source: app/
    destination: /opt/apps/
    overwrite: true
permissions:
  - object: /opt/apps/scripts
    pattern: "*.sh"
    owner: root
    group: root
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: /opt/apps/scripts/stop.sh
      timeout: 3000
      runas: root
    - location: /bin/bash
      timeout: 180
      runas: root
      script: |
        echo "BeforeInstall Hook - Current Directory:"
        pwd
        echo "BeforeInstall Hook - Listing Files:"
        ls -la /opt/apps/scripts
  ApplicationStart:
    - location: /opt/apps/scripts/start.sh
      timeout: 180
      runas: root




