version: 0.0
os: linux

files:
  - source: ./
    destination: /opt/apps
    overwrite: true  # Ensure files are overwritten if they exist

hooks:
  AfterInstall:
    - location: scripts/start.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
