name: Deploy to AWS (Development)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-north-1
      APPLICATION_NAME: CodeDeployApp
      DEPLOYMENT_GROUP: development
      S3_BUCKET: myawsbucketdemonst

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build project
        run: |
          cd app
          zip -r ../myapp-dev.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          audience: sts.amazonaws.com
        env:
          AWS_DEFAULT_REGION: eu-north-1
          APPLICATION_NAME: CodeDeployApp
          DEPLOYMENT_GROUP: development
          S3_BUCKET: myawsbucketdemonst

      - name: Upload to S3
        run: aws s3 cp myapp-dev.zip s3://${{ env.S3_BUCKET }}/development/myapp-dev.zip

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.APPLICATION_NAME }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ env.S3_BUCKET }},bundleType=zip,key=development/myapp-dev.zip \
            --file-exists-behavior OVERWRITE \
            --region ${{ env.AWS_DEFAULT_REGION }}
