name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Development
        run: |
          cd app
          zip -r ../myapp-dev.zip *
        working-directory: ${{ github.workspace }}
        if: github.ref == 'refs/heads/main'

      - name: Build for Production
        run: |
          cd app
          zip -r ../myapp-prod.zip *
        working-directory: ${{ github.workspace }}
        if: github.ref == 'refs/heads/main'

      - name: Upload to S3 for Development
        uses: actions/aws/cli@v1
        with:
          args: s3 cp myapp-dev.zip s3://${{ secrets.S3_BUCKET }}/development/myapp-dev.zip
        if: github.ref == 'refs/heads/main'

      - name: Upload to S3 for Production
        uses: actions/aws/cli@v1
        with:
          args: s3 cp myapp-prod.zip s3://${{ secrets.S3_BUCKET }}/production/myapp-prod.zip
        if: github.ref == 'refs/heads/main'

      - name: Deploy to Development
        uses: aws-actions/aws-codedeploy-github-actions@v1
        with:
          application-name: ${{ secrets.APPLICATION_NAME }}
          deployment-group: ${{ secrets.DEV_DEPLOYMENT_GROUP }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          wait-until-deployed: true
          s3-bucket: ${{ secrets.S3_BUCKET }}
          bundle-type: zip
          key: development/myapp-dev.zip
        if: github.ref == 'refs/heads/main'

      - name: Deploy to Production
        uses: aws-actions/aws-codedeploy-github-actions@v1
        with:
          application-name: ${{ secrets.APPLICATION_NAME }}
          deployment-group: ${{ secrets.PROD_DEPLOYMENT_GROUP }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          wait-until-deployed: true
          s3-bucket: ${{ secrets.S3_BUCKET }}
          bundle-type: zip
          key: production/myapp-prod.zip
        if: github.ref == 'refs/heads/main'
