name: Deploy to AWS (Development)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build project
        run: |
          cd app
          zip -r ../myapp-dev.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp myapp-dev.zip s3://${{ env.S3_BUCKET }}/development/myapp-dev.zip

      - name: Deploy to AWS CodeDeploy
        uses: aws-actions/aws-codedeploy-github-actions@v2.0.4
        with:
          application-name: ${{ env.APPLICATION_NAME }}
          deployment-group: ${{ env.DEPLOYMENT_GROUP }}
          revision-location: s3://${{ env.S3_BUCKET }}/development/myapp-dev.zip
          region: ${{ env.AWS_DEFAULT_REGION }}
