name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build for Production
        run: |
          cd app
          zip -r ../myapp-prod.zip *
        working-directory: ${{ github.workspace }}
        env:
          NODE_ENV: production

      - name: Upload to S3 for Production
        run: aws s3 cp myapp-prod.zip s3://${{ secrets.S3_BUCKET }}/production/myapp-prod.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to Production
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.PROD_DEPLOYMENT_GROUP }} \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=production/myapp-prod.zip,bundleType=zip \
            --region ${{ secrets.AWS_DEFAULT_REGION }} \
            --ignore-application-stop-failures \
            --file-exists-behavior OVERWRITE \
            --wait
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
