name: Deploy to AWS

on:
  push:
    branches:
      - main
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Determine deployment environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "NODE_ENV=development" >> $GITHUB_ENV
            echo "CONFIG_FILE=config.dev.json" >> $GITHUB_ENV
            echo "DEPLOYMENT_GROUP=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "NODE_ENV=production" >> $GITHUB_ENV
            echo "CONFIG_FILE=config.prod.json" >> $GITHUB_ENV
            echo "DEPLOYMENT_GROUP=production" >> $GITHUB_ENV
          fi

      - name: Zip application
        run: zip -r app.zip .

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws s3 cp app.zip s3://myawsbucketdemonst/${{ env.DEPLOYMENT_GROUP }}/app.zip

      - name: Deploy to CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws deploy create-deployment \
            --application-name GitApp \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
            --s3-location bucket=myawsbucketdemonst,key=${{ env.DEPLOYMENT_GROUP }}/app.zip,bundleType=zip
