name: Deploy to S3 and CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to the app directory and zip files
        run: |
          cd app
          zip -r app.zip appspec.yml scripts/
          mv app.zip ..
      
      - name: Upload to S3
        run: aws s3 cp app.zip s3://myawsbucketdemonst/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
      
      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployApp \
            --deployment-group-name CodeDeployGroup \
            --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
