name: Deploy to S3 and CodeDeploy

on:
  push:
    branches:
      - main
      - release

jobs:
  build_and_deploy_dev:
    name: Build and Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run for main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Development
        run: |
          cd app
          zip -r myapp-dev.zip .
          ls -la ../  # Verify file location for troubleshooting

      - name: Upload to S3 for Development
        run: |
          aws s3 cp myapp-dev.zip s3://myawsbucketdemonst/development/myapp-dev.zip --region eu-north-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Deploy to Development
        run: |
          aws deploy create-deployment \
            --application-name GitApp \
            --deployment-group-name development \
            --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=development/myapp-dev.zip \
            --region 'ap-south-1'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
          DEPLOYMENT_GROUP_NAME: 'development'  # Set the deployment group name
