name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Zip build files
      run: zip -r my-node-app.zip .

    - name: Upload to S3 (Development)
      if: github.ref == 'refs/heads/main'
      run: aws s3 cp my-node-app.zip s3://myawsbucketdemonst/development/my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

    - name: Upload to S3 (Production)
      if: github.ref == 'refs/heads/release'
      run: aws s3 cp my-node-app.zip s3://myawsbucketdemonst/production/my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download from S3 (Development)
      if: github.ref == 'refs/heads/main'
      run: aws s3 cp s3://myawsbucketdemonst/development/my-node-app.zip my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

    - name: Download from S3 (Production)
      if: github.ref == 'refs/heads/release'
      run: aws s3 cp s3://myawsbucketdemonst/production/my-node-app.zip my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

    - name: zip files
      run: zip my-node-app.zip -d .

    - name: Deploy to CodeDeploy (Development)
      if: github.ref == 'refs/heads/main'
      run: aws deploy create-deployment --application-name GitApp --deployment-group-name grps --deployment-config-name CodeDeployDefault.OneAtATime --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=development/my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'

    - name: Deploy to CodeDeploy (Production)
      if: github.ref == 'refs/heads/release'
      run: aws deploy create-deployment --application-name GitApp --deployment-group-name production --deployment-config-name CodeDeployDefault.OneAtATime --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=production/my-node-app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-south-1'
