name: Deploy to S3 and CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Upload to S3
        run: |
          zip -r app.zip appspec.yml start.sh stop.sh deploy.sh other_files
          aws s3 cp app.zip s3://myawsbucketdemonst/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployApp \
            --deployment-group-name CodeDeployGroup \
            --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
