name: Deploy to S3 and CodeDeploy

on:
  push:
    branches:
      - main
      - release

jobs:
  build_and_deploy_dev:
    name: Build and Deploy to Development
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run for main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Development
        run: |
          cd app
          zip -r myapp-dev.zip .
          mv myapp-dev.zip ..

      - name: Upload to S3 for Development
        run: |
          aws s3 cp myapp-dev.zip s3://myawsbucketdemonst/development/myapp-dev.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Deploy to Development
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployApp \
            --deployment-group-name development \
            --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=development/myapp-dev.zip \
            --region 'eu-north-1'  # Adjust region as needed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
          DEPLOYMENT_GROUP_NAME: 'development'  # Set the deployment group name

  build_and_deploy_prod:
    name: Build and Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'  # Only run for release branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Production
        run: |
          cd app
          zip -r myapp-prod.zip .
          mv myapp-prod.zip ..

      - name: Upload to S3 for Production
        run: |
          aws s3 cp myapp-prod.zip s3://myawsbucketdemonst/production/myapp-prod.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'

      - name: Deploy to Production
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployApp \
            --deployment-group-name production \
            --s3-location bucket=myawsbucketdemonst,bundleType=zip,key=production/myapp-prod.zip \
            --region 'eu-north-1'  # Adjust region as needed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-north-1'
          DEPLOYMENT_GROUP_NAME: 'production'  # Set the deployment group name